services:
  weaviate:
    container_name: weaviate
    image: semitechnologies/weaviate:latest
    restart: no
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      HOSTNAME: 0.0.0.0
      CLUSTER_HOSTNAME: 'node1'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-openai'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      OPENAI_APIKEY: '${OPENAI_APIKEY}'
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
